### ISSUE TITLE
ModuleNotFoundError: 'PySide2.support.signature.inspect' with PySide2 (5.11.2)

### ISSUE THREAD

**Issue by Chaz6** [bvirxx/bLUe_PYSIDE2#1]
```
$ pip3.6 install -U --user PySide2
Requirement already up-to-date: PySide2 in /home/chaz/.local/lib/python3.6/site-packages (5.11.2)
$ python3.6 ./bLUe.py
Traceback (most recent call last):
  File "./bLUe.py", line 131, in <module>
    from grabcut import segmentForm
  File "/home/chaz/git/github.com_bvirxx_bLUe_PYSIDE2/grabcut.py", line 24, in <module>
    from MarkedImg import vImage
  File "/home/chaz/git/github.com_bvirxx_bLUe_PYSIDE2/MarkedImg.py", line 24, in <module>
    from PySide2.support.signature.inspect import getframeinfo, currentframe
ModuleNotFoundError: No module named 'PySide2.support.signature.inspect'
```

**Comment by bvirxx** [comment]
Unused import : removed.
